# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='frameworks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='programming_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
