# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_ensure_user_avatar_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicquestion",
            name="expected_output",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topicquestionanswer",
            name="submitted_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topicquestionanswer",
            name="stdout",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topicquestionanswer",
            name="stderr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topicquestionanswer",
            name="exit_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
